"""Added readiness column to User model

Revision ID: 18dc7285de70
Revises: 
Create Date: 2023-10-09 22:40:09.953972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dc7285de70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readiness', sa.String(length=10), nullable=True))
        batch_op.drop_column('ready_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready_status', sa.VARCHAR(length=15), server_default=sa.text("'Not Ready'"), nullable=True))
        batch_op.drop_column('readiness')

    # ### end Alembic commands ###
